name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Run tests
      run: |
        . .venv/bin/activate
        pytest -q

  integration:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Start Compose stack
        run: |
          docker compose up --build -d

      - name: Run integration pytest
        run: |
          pytest -q app/tests/test_integration.py

      - name: Tear down
        if: always()
        run: |
          docker compose down
